---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: dev
  labels:
     app: javaapp
     type: front-end
spec:
  template:
    metadata:
     name: java-pod
     labels:
        app: javaapp
        type: front-end
    spec:
      containers:
      - name: java
        image: docker4ranjit/loginwebapp:11

  replicas: 2
  selector:
     matchLabels:
        type: front-end